#######################################################################################
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title                       : The Python Companion of Intuitive Biostatistics
author                      : "Sébastien Wieckowski"
copyright                   : "2024"
logo                        : logo.jpg
exclude_patterns            : [_build, "**.ipynb_checkpoints", pdf, html]

# Auto-exclude files not in the toc
only_build_toc_files        : true

#######################################################################################
# Execution settings
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks         : 'off'

#######################################################################################
# HTML-specific settings
html:
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]

repository:
  url                       : https://github.com/sbwiecko/intuitive_biostatistics  # The URL to your book's repository
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# LaTeX-specific settings
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname              : intuitive-biostatistics-python.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles: 
#   - references.bib

######################################################################################
# Update, build and deploy the Jupyter-book
#
# complete _toc.yml
# >jupyter-book build .
# push the commits to origin/master
# >ghp-import -n -p -f _build/html
